C     $Id$
      SUBROUTINE ANIMES
      RETURN
      END
C
      SUBROUTINE ANIMEE
      RETURN
      END
C
      SUBROUTINE gsglProjImgTranslate (X, Y)
      RETURN
      END
C
      SUBROUTINE gsglProjImgScale (FX, FY)
      RETURN
      END
C
      SUBROUTINE gsglProjImgRotate (ANGLE)
      RETURN
      END
C
      SUBROUTINE gsglProjImgIdentity
      RETURN
      END
C
      SUBROUTINE gsglVecrotText ()
      RETURN
      END
C
      SUBROUTINE gsglPolygonText ()
      RETURN
      END
C
      SUBROUTINE SetFreeTypeNodeNum (N)
      RETURN
      END
C
      SUBROUTINE gsgl_inqcharmath (CHH, CHW)
      RETURN
      END
C
      SUBROUTINE inqtextbbox (ktext, nchar, size, height, depth)
      CHARACTER*256 KTEXT
      CALL INQTSZ(KTEXT, NCHAR, SIZE)
      CALL INQCHR(HEIGHT,CHW,CHSP,ANGL,TILT)
      HEIGHT=HEIGHT*8.0/9.0
      DEPTH=0.0
      RETURN
      END
C
      SUBROUTINE GUIEXTERNAL(IEXT)
      RETURN
      END
C
      SUBROUTINE GUILABEL(X, Y, W, H, TEXT, IJUST)
      CHARACTER*256 TEXT
      RETURN
      END
C     
      SUBROUTINE INQLABELSIZE(TEXT, W, H)
      CHARACTER*256 TEXT
      RETURN
      END
C
      SUBROUTINE GUIBUTTON(X, Y, W, H, TEXT, CALLBACK)
      CHARACTER*256 TEXT
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUICOMBOBOX(X, Y, W, H, NITEM, TEXT, INIT, CALLBACK)
      CHARACTER*256 TEXT
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUISPINBUTTONF(X, Y, W, H, INIT, LOWER, UPPER, DIGITS,
     &     CALLBACK)
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUISPINBUTTONI(X, Y,  W, H, INIT, LOWER, UPPER,
     &     CALLBACK)
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUICHECKBUTTON(X, Y, W, H, TEXT, INIT, CALLBACK)
      CHARACTER*256 TEXT
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUILINEEDIT(X, Y, W, H, MAX, TEXT, NTEXT, CALLBACK)
      CHARACTER*256 TEXT
      EXTERNAL CALLBACK
      RETURN
      END
C
      SUBROUTINE GUIEXITLOOP()
      RETURN
      END
