C
      SUBROUTINE SET3DCOORD_POLAR1 (OX,OY,OZ,RADIUS,THETA,PHI)
      RETURN
      END
C
      SUBROUTINE SET3DCOORD_POLAR2 (WX,WY,DEPTH,X,Y,Z,THETA,PHI)
      RETURN
      END
C
      SUBROUTINE SET3DCOORD_CAUT1 (OX,OY,OZ,DEPTH,VX,VY,VZ)
      RETURN
      END
C
      SUBROUTINE SET3DCOORD_CAUT2 (WX,WY,DEPTH,X,Y,Z,VX,VY,VZ)
      RETURN
      END
C
      SUBROUTINE SETPROJECTIONTYPE (IPROJ)
      RETURN
      END
C
      SUBROUTINE gsglSetEyePos(Z)
      RETURN
      END
C
      SUBROUTINE Set3DTextBaseLine(V1x, V1y, V1z, V2x, V2y, V2z)
      RETURN
      END
C
      SUBROUTINE TEXT3D(KTEXT,NCHR)
      CHARACTER*256 KTEXT
      RETURN
      END
C
      SUBROUTINE TEXTX3D(KTEXTX)
      CHARACTER*256 KTEXTX
      RETURN
      END
C
      SUBROUTINE GTEXT3D(X,Y,Z,KTEXT,NCHAR,IJUST)
      CHARACTER*256 KTEXT
      RETURN
      END
C
      SUBROUTINE GTEXTX3D(X,Y,Z,KTEXTX,IJUST)
      CHARACTER*256 KTEXTX
      RETURN
      END
C
      SUBROUTINE NUMBI3D(I,KFORM,NCHAR)
      CHARACTER KFORM*16
      RETURN
      END
C
      SUBROUTINE NUMBD3D(D,KFORM,NCHAR)
      CHARACTER KFORM*16
      RETURN
      END
C
      SUBROUTINE NUMBR3D(R,KFORM,NCHAR)
      CHARACTER KFORM*16
      RETURN
      END
C
      SUBROUTINE GNUMBI3D(X,Y,Z,I,IJUST)
      RETURN
      END
C
      SUBROUTINE GNUMBD3D(X,Y,Z,D,IND,IJUST)
      RETURN
      END
C
      SUBROUTINE GNUMBR3D(X,Y,Z,R,IND,IJUST)
      RETURN
      END
C
      SUBROUTINE GNUMBP3D(X,Y,Z,I,J,IJUST)
      RETURN
      END
C
      SUBROUTINE GDrawBack3D(R,G,B)
      CALL GDRWBK(R,G,B)
      RETURN
      END
C
      SUBROUTINE GPLOTP3D(GX,GY,GZ,NS,NE,NSTEP,IMARK,ISTEP,IPAT)
      DIMENSION GX(*),GY(*),GZ(*)
      RETURN
      END
C
      SUBROUTINE PERS3D1(Z, NMX, NX, NY, IND, RGBFUNC)
      DIMENSION Z(NMX,*)
      EXTERNAL RGBFUNC
      RETURN
      END
C
      SUBROUTINE PERS3D2(Z, X, Y, NMX, NX, NY, IND, RGBFUNC)
      DIMENSION Z(NMX,*), X(NX), Y(NY)
      EXTERNAL RGBFUNC
      END
C
      SUBROUTINE PERS3D3(Z, R, NMX, NR, NT, IND, RGBFUNC)
      DIMENSION R(NR)
      EXTERNAL RGBFUNC
      END
C
      SUBROUTINE PERS3D4(Z, R, T, NMX, NR, NT, IND, RGBFUNC)
      DIMENSION Z(NMX,*),R(NR),T(NT)
      EXTERNAL RGBFUNC
      RETURN
      END
      SUBROUTINE PERS3D5 (Z, X, Y, NMX, IXMAX, IYMAX, IND, RGBFUNC)
      DIMENSION Z(NMX,*),X(NMX,*),Y(NMX,*)
      EXTERNAL RGBFUNC
      RETURN
      END
C
      SUBROUTINE PERS3DF (Z, X, Y, NNODE, IELM, NELM, IND, RGBFUNC)
      DIMENSION Z(*),X(*),Y(*),IELM(3,*)
      EXTERNAL RGBFUNC
      RETURN
      END
C
      SUBROUTINE R2G2B_17(R)
      RETURN
      END
C
      SUBROUTINE gsglWireSphere(X,Y,Z,VX,VY,VZ,radius,slices,stacks)
      RETURN
      END
C
      SUBROUTINE gsglSolidSphere(X, Y, Z, VX, VY, VZ, R, SLICES, STACKS)
      RETURN
      END
C
      SUBROUTINE gsglWireTorus(X,Y,Z,VX,VY,VZ,InRad,OutRad,Nsides,Rings)
      RETURN
      END
C
      SUBROUTINE gsglSolidTorus(X,Y,Z,VX,VY,VZ,InRad,OutRad,Nsides,Ring)
      RETURN
      END
C
      SUBROUTINE move3D(X,Y,Z)
      RETURN
      END
C
      SUBROUTINE draw3D(X,Y,Z)
      RETURN
      END
C
      SUBROUTINE poly3D(X,Y,Z,N)
      DIMENSION X(N),Y(N),Z(N)
      RETURN
      END
C
      SUBROUTINE rgbtrg3D(X,Y,Z,R,G,B)
      DIMENSION X(3),Y(3),Z(3),R(3),G(3),B(3)
      RETURN
      END
C
      SUBROUTINE lines3D(X,Y,Z,N)
      DIMENSION X(N),Y(N),Z(N)
      RETURN
      END
C
      SUBROUTINE movept3D(X,Y,Z,IPAT)
      RETURN
      END
C
      SUBROUTINE drawpt3D(X,Y,Z)
      RETURN
      END
C
