#!/bin/sh
source=$1
shift

if [ -r "${source}.f" ]
then
	echo "pgf77 ${source}.f -o ${source} $* [graphic libs]"
	pgf77 ${source}.f -o ${source} $* -L/usr/local/lib -lgsp-pgf -lgdum-pgf -L/usr/X11R6/lib -lX11 
else
	echo "pgf77g : source file ${source}.f cannot be found."
fi
